import Navbar from "@/components/Navbar";

import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "@/components/Footer";
import PlaceReservation from "@/components/PlaceReservation";
import { usePathname } from "next/navigation";
import MenuNavbar from "@/components/MenuNavbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const router = usePathname();
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
        />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
        />
      </head>
      <body className={inter.className}>
        {/* Conditional rendering of the navbar based on the current route */}
        {/* {router === "/menu" ? <MenuNavbar /> : <Navbar />} */}
        <Navbar />

        <div
          style={{
            position: "sticky",
            top: "10",
            left: "0",
            right: "0",
            zIndex: "10", // You can adjust this value as needed
          }}
        >
          <PlaceReservation />
        </div>
        {children}
        <Footer />
      </body>
    </html>
  );
}
